# Generated by Django 2.1.5 on 2019-01-23 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='text',
            new_name='content',
        ),
    ]
