# Generated by Django 2.1.5 on 2019-01-23 17:57

from django.db import migrations, models
import django.utils.timezone
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190123_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='about',
            name='status',
            field=models.CharField(choices=[('D', 'Draft'), ('P', 'Published')], default='D', max_length=1),
        ),
        migrations.AddField(
            model_name='about',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='about',
            name='content',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
