# Generated by Django 2.1.5 on 2019-01-23 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190123_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='images',
        ),
    ]
