# Generated by Django 2.1.5 on 2019-01-23 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_about_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='user',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
